// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20_RockPaperScissorsGame_NoDb;

namespace _20_RockPaperScissorsGame_NoDb.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200903225429_CreateRockPaperScissorsDb")]
    partial class CreateRockPaperScissorsDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_20_RockPaperScissorsGame_NoDb.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("p1PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("p2PlayerId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("WinnerPlayerId");

                    b.HasIndex("p1PlayerId");

                    b.HasIndex("p2PlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("_20_RockPaperScissorsGame_NoDb.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("_20_RockPaperScissorsGame_NoDb.Round", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComputerChoice")
                        .HasColumnType("int");

                    b.Property<int?>("Game_IdGameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerChoice")
                        .HasColumnType("int");

                    b.Property<int?>("winnerPlayerId")
                        .HasColumnType("int");

                    b.HasKey("RoundId");

                    b.HasIndex("Game_IdGameId");

                    b.HasIndex("winnerPlayerId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("_20_RockPaperScissorsGame_NoDb.Game", b =>
                {
                    b.HasOne("_20_RockPaperScissorsGame_NoDb.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerId");

                    b.HasOne("_20_RockPaperScissorsGame_NoDb.Player", "p1")
                        .WithMany()
                        .HasForeignKey("p1PlayerId");

                    b.HasOne("_20_RockPaperScissorsGame_NoDb.Player", "p2")
                        .WithMany()
                        .HasForeignKey("p2PlayerId");
                });

            modelBuilder.Entity("_20_RockPaperScissorsGame_NoDb.Round", b =>
                {
                    b.HasOne("_20_RockPaperScissorsGame_NoDb.Game", "Game_Id")
                        .WithMany()
                        .HasForeignKey("Game_IdGameId");

                    b.HasOne("_20_RockPaperScissorsGame_NoDb.Player", "winner")
                        .WithMany()
                        .HasForeignKey("winnerPlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
